#!/bin/bash

ORIGIN=$(pwd)

CMAKE_BUILD_DIR=".build"
OUTPUT_DIR="output"

if [ ! -d "$CMAKE_BUILD_DIR" ]; then
  mkdir ${CMAKE_BUILD_DIR}
fi

if [ ! -d "$OUTPUT_DIR" ]; then
  mkdir ${OUTPUT_DIR}
fi

cd ${CMAKE_BUILD_DIR}

cmake ${ORIGIN}
make
mv prog* ${ORIGIN}/${OUTPUT_DIR}
