#!/bin/bash

## Managing default directories, args etc...

ORIGIN=$(pwd)

DEFAULT_CMAKE_BUILD_DIR=".build"
DEFAULT_BIN_DIR="bin"
DEFAULT_OUTPUT_DIR="output"

CMAKE_BUILD_DIR=$1
BIN_DIR=$2
OUTPUT_DIR=$3

if [ -z "$CMAKE_BUILD_DIR" ]; then
	CMAKE_BUILD_DIR=${DEFAULT_CMAKE_BUILD_DIR}
fi

if [ -z "$BIN_DIR" ]; then
	BIN_DIR=${DEFAULT_BIN_DIR}
fi

if [ -z "$OUTPUT_DIR" ]; then
	OUTPUT_DIR=${DEFAULT_OUTPUT_DIR}
fi

## Build everything

echo
echo "-= IT'S BENCH TIME =-"
echo

./build ${CMAKE_BUILD_DIR} ${OUTPUT_DIR}

## Run benchmarks

echo ${BIN_DIR}
ls ${ORIGIN}/${BIN_DIR}

EXEC_LIST=$(ls ${ORIGIN}/${BIN_DIR})

for BENCH_EXEC in ${EXEC_LIST}; do
	${BIN_DIR}/${BENCH_EXEC} --benchmark_repetitions=10 --benchmark_report_aggregates_only=true --benchmark_format=json --benchmark_out=${ORIGIN}/${OUTPUT_DIR}/${BENCH_EXEC}_report.json
done
