#!/bin/bash

## Managing default directories, args etc...

ORIGIN=$(pwd)

DEFAULT_CMAKE_BUILD_DIR=".build"
DEFAULT_BIN_DIR="bin"

CMAKE_BUILD_DIR=${1}
BIN_DIR=${2}

if [ -z "${CMAKE_BUILD_DIR}" ]; then
	CMAKE_BUILD_DIR=${DEFAULT_CMAKE_BUILD_DIR}
fi

if [ -z "${BIN_DIR}" ]; then
	BIN_DIR=${DEFAULT_BIN_DIR}
fi

## Making sure directories are there

if [ ! -d "$CMAKE_BUILD_DIR" ]; then
  mkdir ${CMAKE_BUILD_DIR}
fi

if [ ! -d "$BIN_DIR" ]; then
  mkdir ${BIN_DIR}
fi

## *puts on sunglasses*

cd ${CMAKE_BUILD_DIR}

echo
echo "-= Aye let's build =-"
echo

cmake ${ORIGIN}
make
mv prog* ${ORIGIN}/${BIN_DIR}

rm ${ORIGIN}/${BIN_DIR}/*.asm

EXEC_LIST=$(ls ${ORIGIN}/${BIN_DIR})

for DUMP_EXEC in ${EXEC_LIST}; do
	objdump -dC ${ORIGIN}/${BIN_DIR}/${DUMP_EXEC} > ${ORIGIN}/${BIN_DIR}/${DUMP_EXEC}.asm
done
